### PR TITLE
BlendmapShader

### PR DESCRIPTION
**Pull request by boombuler**
This will implement the feature requested in #231

### CODE REVIEW

**Comment by Noofbiz** [comment]
I get a panic when I try to build when it tries to compile the shader:

```
$ go run --tags=demo *.go
panic: an error occurred compiling the fragment shader: ERROR: 0:20: Invalid call of undeclared identifier 'textureSize'
ERROR: 0:21: Invalid call of undeclared identifier 'textureSize'
ERROR: 0:22: Use of undeclared identifier 'sMap'
ERROR: 0:22: Use of undeclared identifier 'sChan'
ERROR: 0:23: Use of undeclared identifier 'sMap'
ERROR: 0:23: Use of undeclared identifier 'sChan'
ERROR: 0:25: Use of undeclared identifier 'x'
ERROR: 0:25: Use of undeclared identifier 'y'


goroutine 1 [running, locked to thread]:
engo.io/engo/common.(*RenderSystem).New(0xc00007d770, 0xc00007ca20)
	/Users/noofapple/go/src/engo.io/engo/common/render.go:214 +0x1eb
engo.io/ecs.(*World).AddSystem(0xc00007ca20, 0x43244c0, 0xc00007d770)
	/Users/noofapple/go/src/engo.io/ecs/world.go:18 +0x157
main.(*DefaultScene).Setup(0x45631e0, 0x4323980, 0xc00007ca20)
	/Users/noofapple/go/src/engo.io/engo/demos/isoadventure/iso.go:69 +0xc5
engo.io/engo.SetScene(0x4325980, 0x45631e0, 0x4112800)
	/Users/noofapple/go/src/engo.io/engo/scene.go:112 +0x2ff
engo.io/engo.RunPreparation(0x4325980, 0x45631e0)
	/Users/noofapple/go/src/engo.io/engo/engo_glfw.go:254 +0x53
engo.io/engo.runLoop(0x4325980, 0x45631e0, 0x100)
	/Users/noofapple/go/src/engo.io/engo/engo_glfw.go:266 +0x121
engo.io/engo.Run(0x0, 0x42f2398, 0x1d, 0x0, 0x1f4, 0x1f4, 0x3f8000003f800000, 0x0, 0x3c, 0x0, ...)
	/Users/noofapple/go/src/engo.io/engo/engo.go:229 +0x416
main.main()
	/Users/noofapple/go/src/engo.io/engo/demos/isoadventure/iso.go:353 +0xd6
exit status 2
```

**Comment by boombuler** [comment]
Works on my machine... But I'll have a look tomorrow. Thx for the feedback

**Comment by Noofbiz** [comment]
The issue is that osx and ios don't implement the textureSize glsl built in. I think we could use a polyfill that should work pretty easy

'''
#if VERSION < 130
uniform vec2 textureSz;
vec2 textureSize(in unusedSampler) {
return textureSz;
}
#endif
'''

And pass textureSz as the drawable's width / height

**Comment by boombuler** [comment]
It might be better to calc the scale factor on cpu side anyway since it
will not change for each fragment...

Am Mi., 27. Feb. 2019 um 02:39 Uhr schrieb Noofbiz <notifications@github.com

**Comment by Noofbiz** [comment]
Awesome, works great for me now ^_^!

**Pull request merged**
