### PR TITLE
Reverse android bindings

### PR DESCRIPTION
**Pull request by Noofbiz**
Allows you to build an android (and possibly ios but don't have access to a Mac) library that uses Engo as part of a GlSurfaceView in Android. In currently working on a tutorial for it's use on github.com/Noofbiz/mousetests. I'll update on here when the full tutorial is done. Basically you can create a library that's a replica of the main function except instead use Start(int, int) instead of main. Then create an android glue library within the project that gets called from Java. Then you can build the library package using gomobile bind -tags=mobilebind
This will generate the  . aar file that you add to your Java code for Android. I'll try to get the full tutorial up sometime this evening, but you guys can check out the code now and let me know if you have any comments or suggestions.

### CODE REVIEW

**Comment by paked** [comment]
Wow. This sounds awesome!

Let me know when you've got the tutorial up, and I'll take a flick through.

**Comment by paked** [comment]
Will try to review/merge in a few hours, once tests are passing. Feel free to pester me if I forget.

**Comment by Noofbiz** [comment]
Keeps saying that stdlib isn't found on the test build

**Comment by Noofbiz** [comment]
Looks like it's failing due to this maybe? 
https://github.com/golang/go/issues/21802

**Comment by Noofbiz** [comment]
That PR recommends clearing out the exact folder we're caching via the travis.yml
Could someone with access to it, go on and clear the cache?
https://docs.travis-ci.com/user/caching/

**Comment by Noofbiz** [comment]
Okay, so it appears that is due to the update (and maybe a few more problems, sheesh!) While I work on getting that fixed, the tutorial on getting it to run via Android Studio is now available ^_^!
It's the readme for https://github.com/Noofbiz/MouseTests

**Comment by paked** [comment]
Just merged the other PR you submitted. Let me know if I can do anything else to help :)

**Comment by Noofbiz** [comment]
Oh this also implements using binary data, because the mobile with bindings is cut off from the file system for security. It solves #400

**Pull request merged**
