### PR TITLE
Tile layer name

### PR DESCRIPTION
**Pull request by randomandy**
Added LayerName to common.tile struct (for Tiles and Images)

### CODE REVIEW

**Comment by randomandy** [comment]
Basic fix for #353

**Comment by otraore** [comment]
It LGTM, I'm going to leave it open to see the thoughts of other people. I assume you also tested this out? But with that said It would be nice if you can add in support for all the data available in the tmx layer element to our [TMXLayer](https://github.com/EngoEngine/engo/blob/master/common/tmx_level.go#L35) object. Also maybe have a way to get the layer from the tile object rather than layer properties on the tile. . Eventually we want to support the [full tmx specification](http://doc.mapeditor.org/reference/tmx-map-format/) so this would help a lot.

**Comment by randomandy** [comment]
Ok I'm gonna try to get the full specs done this weekend. If you want you can merge this one, and I'm gonna create a new PR when I'm done with the rest.

**Comment by otraore** [comment]
@randomandy I would appreciate it if you at least covered the Layer spec in this PR since that's the one it's focused on. Don't need to do it for every element in this PR but at least for the Layer one. Thank you again, appreciate it.

**Comment by randomandy** [comment]
I'm closing this PR for now as I'm adding the full feature set we discussed earlier and in #353 . Gonna open a new PR as soon as it's all done and tested

**Comment by paked** [comment]
Awesome!

**Comment by randomandy** [comment]
Done, please see #357 for details

**Pull request closed without merging**
