### PR TITLE
Fix framebuffer scale issue for OSX retina

### LINKED ISSUE #379: [Two Error] OSX Mouse ,Android don't work
in osx,run pong,the mouse exist deviation.
osx 10.11.6 
macbook pro 15 retina

in android, `mouse`  demos  don't work

### LINKED ISSUE #388: Mouse scaling is way off on OSX (maybe Retina issue?)
I'm working through the Traffic tutorial, and I've written the code in Tutorial 2.  On OSX, the mouse positioning seems to be WAY off.  In the attached screenshot, I pressed "F1" with the mouse cursor 
on each corner of the game window.  The placed cities show how far off those clicks were. I think this is the same thing that the first bit of #379 is talking about.

> in osx,run pong,the mouse exist deviation.
> osx 10.11.6 
> macbook pro 15 retina

screen shot 2016-09-23 at 4 57 25 pm

### PR DESCRIPTION
**Pull request by kyhavlov**
There were a few things wrong with the code for scaling window size vs canvas size; the canvas (frame buffer) size was getting conflated with window size in `SetFramebufferSizeCallback`, and some of the code dealing with mouse coords was missing the scale factor. The last change was to adjust the scale of the projection matrix in the shaders to match the adjusted mouse coords. I wasn't sure if there was a better way to do this, but adjusting these few cases in `render_shaders.go` works. 

Fixes #379 
Fixes #388

### CODE REVIEW

**Comment by kyhavlov** [comment]
Not sure what's up with the Travis failure, something might be misconfigured there

**Comment by paked** [comment]
```
common/render_shaders.go:161:58: CanvasScale not declared by package engo
common/render_shaders.go:162:60: CanvasScale not declared by package engo
common/render_shaders.go:481:58: CanvasScale not declared by package engo
common/render_shaders.go:482:60: CanvasScale not declared by package engo
common/render_shaders.go:912:58: CanvasScale not declared by package engo
common/render_shaders.go:913:60: CanvasScale not declared by package engo
```

@kyhavlov: I think the error might come from building `engo` with `gopherjs`. This doesn't really make sense though, as it isn't being built...

**Comment by paked** [comment]
```
GLFW: An uncaught error has occurred: PlatformError: Linux: Failed to watch for joystick connections in /dev/input: No such file or directory
GLFW: Please report this bug in the Go package immediately.
2017/01/19 08:25:46 PlatformError: Linux: Failed to open joystick device directory /dev/input: No such file or directory
Xlib:  extension "RANDR" missing on display ":99.0".
--- PASS: TestShadersInitialization (0.05s)
=== RUN   TestShaderCompilation
GLFW: An uncaught error has occurred: PlatformError: Linux: Failed to watch for joystick connections in /dev/input: No such file or directory
GLFW: Please report this bug in the Go package immediately.
2017/01/19 08:25:46 PlatformError: Linux: Failed to open joystick device directory /dev/input: No such file or directory
Xlib:  extension "RANDR" missing on display ":99.0".
```

GLFW is also throwing these errors... I don't think it is responsible for the demo not building though.

Have you tried building this PR on linux?

**Comment by kyhavlov** [comment]
The demo build error is definitely from building with gopherjs; I'm not sure what to do about it though. 
I haven't tried building on Linux with this (don't have a setup for that at the moment). Those joystick errors don't seem related to these changes; I can see them in other PR Travis runs.

**Comment by paked** [comment]
Did you add a stub of your `CanvasScale` function to the `engo_js.go` file?

**Comment by kyhavlov** [comment]
Yeah, I missed adding that stub for js/mobile. Mobile seems to fail even with it though; any ideas there?

**Comment by paked** [comment]
@kyhavlov: Nope. No idea.

@otraore, @EtienneBruines: Can you think of anything?

**Comment by otraore** [comment]
It's causing all new issues to fail, possible solutions include downloading the android NDK to test mobile builds. Or not test mobile. Adding the NDK increases the time it take tests to run by about a minute.

**Comment by otraore** [comment]
Working on it in: https://github.com/EngoEngine/engo/pull/406

**Comment by kyhavlov** [comment]
Does this fix look good to merge now? @paked @otraore

**Comment by paked** [comment]
@kyhavlov: Thanks for this. Sorry it took so long to merge :)

**Comment by kyhavlov** [comment]
No problem, thanks for all your work maintaining this!

**Pull request merged**
