### PR TITLE
Fix RenderComponent constructor

### PR DESCRIPTION
**Pull request by paked**
Thank you @mewmew for pointing this out.

### CODE REVIEW

**Comment by paked** [comment]
DNM Until demos are fixed.

**Comment by paked** [comment]
ready to go!

**Comment by Newbrict** [comment]
looks good to me, but why remove the label? what was the reason we needed it initially?

**Comment by paked** [comment]
Response from Gitter.

> paked: @Newbrict I didn't remove the label, the label was removed a while back... Unfortunately it was left in the constructor.
> paked: It was originally used for associating resources with displaycomponents
> paked: If I remember correctly...

**Comment by EtienneBruines** [comment]
LGTM. Thank you for fixing it. 

https://github.com/EngoEngine/engo/pull/216 would have also fixed it, but it's good to have it fixed before having to wait for such long-standing PR.

**Pull request merged**
