### PR TITLE
Add Width() and Height() to breaking changes

### PR DESCRIPTION
**Pull request by otraore**

### CODE REVIEW

**Comment by EtienneBruines** [comment]
LGTM. Do you also want to change the `gopherjs` in this PR, or do you want a separate PR for that?

**Comment by otraore** [comment]
Huh?

**Comment by EtienneBruines** [comment]
@otraore 
https://github.com/EngoEngine/engo/blob/master/engo_js.go#L96

**Comment by otraore** [comment]
@EtienneBruines Didn't you add that in the rotation PR?

**Comment by EtienneBruines** [comment]
Awesome, nice work @otraore! :smile:

**Pull request merged**
