### PR TITLE
common: godoc comments fix in common/intefaces.go

### PR DESCRIPTION
**Pull request by jrmiller82**
Added whitespace to make the Overview section in godoc for package common render much nicer. Faces, Ables, etc., now are nice headings in godoc. 

Also added punctuation to make the comments complete sentences. 

Also reflowed the comments.

### CODE REVIEW

**Comment by jrmiller82** [comment]
No idea why appveyor is failing... I literally only changed some comments. No code.

**Comment by Noofbiz** [comment]
This can be fixed by closing and reopening the request sometimes. I'm going to try it.

**Comment by jrmiller82** [comment]
Looks like that fixed it. Thanks!

**Comment by Noofbiz** [comment]
Thank you for your contributions

**Pull request merged**
