### PR TITLE
Fix Issue #463: add right mouse dragging to common/mouse.go

### PR DESCRIPTION
**Pull request by jrmiller82**
Code is pretty simple. Added a new External bool to common.MouseComponent and one Internal bool. Mimiced the left mouse stuff for the right mouse stuff. 

Working great on my WIP game.

### CODE REVIEW

**Comment by jrmiller82** [comment]
Looks like I need to rebase this PR onto master. My apologies. Give me a few minutes.

**Comment by jrmiller82** [comment]
Rebased onto current master. :) (Sorry, I'm getting the hang of github.com; I mostly use private bitbucket repos).

**Comment by Noofbiz** [comment]
Looks good, thank you for your addition!

**Comment by jrmiller82** [comment]
You're most welcome. Thanks for all your work on engo!

**Pull request merged**
