### PR TITLE
add support `MovieClip` format

### PR DESCRIPTION
**Pull request by ilyar**
Add support `MovieClip` format for detail see demo and [readme](https://github.com/ilyar/engo/blob/d633c77899ac5a3a23ae2687c21dda412cc3281b/demos/animation-movie-clip/README.md)

Still unresolved issues:

- [ ] It was not possible to create an animation center binding, in the current demo you can see how the center moves with the animation. I tried to calculate the center of the sprite at the time the Spritesheet file was created, but there was a slight tremor.
- [ ] move in `engo/common`
- [ ] delete not used sample formats

I will be glad to review, test and recommendations.

### CODE REVIEW

**Comment by ilyar** [comment]
Video Egret Preview vs Demo
[Egret Preview vs Demo](https://www.youtube.com/watch?v=ZYzpR_9DFeU)

**Comment by Noofbiz** [comment]
Awesome! Looks fantastic so far. Is there any reason you can’t just put the stuff in `engo/formats/mc`in `engo/common’?

**Comment by ilyar** [comment]
> Is there any reason you can’t just put the stuff in engo/formats/mcin `engo/common’?

I began to do so, I realized that because of the common space, all types must be called with a prefix.

```go
package common

func UnmarshalMovieClip(data []byte) (MovieClip, error) {}
type MovieClip struct {}
type ActionMovieClip struct {}
...
```

```go
package mc

func Unmarshal(data []byte) (MovieClip, error) {}
type MovieClip struct {}
type Action struct {}
...
```

There are no other reasons if you want, I do everything in `common`

**Comment by ilyar** [comment]
attempt to fix animation center problem
[Egret Preview vs Demo](https://www.youtube.com/watch?v=mJ4TIAuWjuw)

**Comment by ilyar** [comment]
> marked this pull request as ready for review 5 hours ago

@Noofbiz it's not ready see the checklist in the description

**Comment by Noofbiz** [comment]
Sorry! Must have mis clicked something when I was looking at it somewhere. Disregard that, it was an accident lol

**Comment by ilyar** [comment]
[Egret Preview vs Demo](https://www.youtube.com/watch?v=MjRh1hU2aiM)
Sorry but this is not possible.

After an additional experiment, I made sure that the editor does not correctly calculate the coordinates in the export format and it is simply impossible to complete the format implementation correctly without reliable data.

In addition, support to support the format of sprite animation is unpromising since the larger and more complex the animation, the larger the final texture file.

It is more promising to implement support for other formats, such as Spine, DragonBones Json or perhaps there are others that I do not know about.

I will continue my research.

Tell us about other free animation editors if you know.

**Comment by Noofbiz** [comment]
No worries. I'm not sure about sprite animation, but motion tweening using general shapes should be possible. It's quite a ways to go, but the plan is to add more shapes to the shapes in common, then you could add those to a mention tweening library that can move them around the screen.

**Comment by ilyar** [comment]
I'm sorry, I did not understand your comment.

**Comment by ilyar** [comment]
> No worries.

I'm ok. 


> I'm not sure about sprite animation, but motion tweening using general shapes should be possible. 

I too, the only problem is the editor (DragonBones) that creates the wrong format.

There is no other editor, maybe I will return to implementation when there is a reliable way to create this format.

I also have doubts that the format `MovieClip` is relevant, as far as I can see it is an obsolete format that no one uses. Correct me if I am wrong. 

I thought it would be easy to do without counting on a trap.

> It's quite a ways to go, but the plan is to add more shapes to the shapes in common, then you could add those to a mention tweening library that can move them around the screen.

I did not understand your comment.

**Comment by Noofbiz** [comment]
Oh, as of now engo can draw lines, triangles, rectangles, and ellipses directly to the screen using OpenGL. If I can add arcs and beizer curves I believe that will cover all the basic operations in the SVG spec. Once that's done, we could draw svgs directly to the screen, and use a tweening system to animate them ^_^ That was my idea, anyway :P

**Comment by ilyar** [comment]
Clear it's great.

**Comment by ilyar** [comment]
Am I interested in the current capabilities of the engo enough to implement format [Spine](http://esotericsoftware.com/spine-json-format)  or  [DragonBones JSON](https://github.com/DragonBones/Tools/blob/master/doc/dragonbones_json_format_5.5.md) support  ? This requires mesh-based texture transformation tools. As far as I figured out for this in the current animation system there is not enough component space this is at least.

**Pull request closed without merging**
